echo "Welcome to Employee Wage Computation program on Master Branch"
echo "Check Employee is Present or Absent"
echo "-Use ((RANDOM)) for Attendance Check"
echo "Calculate Daily Employee Wage"
echo	"-Assume Wage per Hour is 20"
echo	"-Assume Full Day Hour is 8"
