echo "Welcome to Employee Wage Computation program on Master Branch"
echo "Check Employee is Present or Absent"
echo "-Use ((RANDOM)) for Attendance Check"
echo "Calculate Daily Employee Wage"
echo	"-Assume Wage per Hour is 20"
echo	"-Assume Full Day Hour is 8"
echo "Add Part time Employee and Wage"
echo	"-Assume Part time Hour is 8"
echo "Solving using Switch Case Statement"
echo "Calculating Wages for a MOnth"
echo	"-Assume 20 Working Day per Month"
echo "Calculate Wages till a condition of total working hours or days is reached for month"
echo	"-Assume 100 hours and 20 days"

